### ISSUE TITLE
File "pyzed/sl.pyx", line 5000, in pyzed.sl.InitParameters.camera_image_flip.__set__ TypeError: Argument must be of FLIP_MODE type.

### ISSUE THREAD

**Issue by dh-bccw** [stereolabs/zed-pytorch#7]
(pytorch1) dh-ununtu-64@dhununtu64-HP:~/zedcamera/zed-pytorch$ python zed_object_detection.py --svo-filename path/to/svo_file.svo
Loading SVO file path/to/svo_file.svo
Traceback (most recent call last):
  File "zed_object_detection.py", line 292, in <module>
    main()
  File "zed_object_detection.py", line 208, in main
    init_cap_params.camera_image_flip = True #False
  File "pyzed/sl.pyx", line 5000, in pyzed.sl.InitParameters.camera_image_flip.__set__
TypeError: Argument must be of FLIP_MODE type.
Someone can help me?  Thankyou!

**Comment by qt-truong** [comment]
Hi @dh-bccw,

There was indeed an issue in the `zed_object_detection.py` script you were using, which was not updated with the latest version of the ZED Python API (the parameter camera_image_flip now takes a [sl.FLIP_MODE](https://www.stereolabs.com/docs/api/python/classpyzed_1_1sl_1_1FLIP__MODE.html) enum value). It has been fixed in commit [#e72b588](https://github.com/stereolabs/zed-pytorch/commit/e72b588719e99b5e03b8d1ca4932829e00ab7f23). 
Thanks for reporting !
